### ISSUE TITLE
Signing releases

### ISSUE THREAD

**Issue by cinemast** [open-source-parsers/jsoncpp#150]
Could you attach gpg signatures to your releases?

e.g. using 
```sh
gpg --armor --detach-sign 1.3.0.tar.gz
```
The resulting file `1.3.0.tar.gz.asc` can then easily be added to the release via the file upload to attach "binaries" provided by github.

**Comment by cinemast** [comment]
How can I help you with that?

**Comment by cdunn2001** [comment]
I need help from other team members. I expect it to take a couple months for us to change our methodology. The code reversions have priority. Is this a blocker?

**Comment by cinemast** [comment]
No not at all, just something that is common in debian packaging now.

**Comment by cdunn2001** [comment]
`0.8.0` is signed. Please let me know if that works before I sign other releases. I uploaded the pgp public key `1E069516` to `keys.gnupg.net`.

**Comment by cinemast** [comment]
```
gpg --verify jsoncpp-0.8.0.tar.gz.asc
gpg: assuming signed data in `jsoncpp-0.8.0.tar.gz'
gpg: Signature made Wed 11 Feb 2015 06:49:44 PM CET using RSA key ID 1E069516
gpg: Good signature from "Christopher Dunn <cdunn2001@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 3FA3 3EE4 5C47 551D 6342  91E8 BE47 603D 1E06 9516
```

Looks Good!

**Comment by cdunn2001** [comment]
Thanks, Peter.

**Comment by cinemast** [comment]
Hi!

Your current release 0.10.2 does not verify against the signature. Could you take a look at that?

**Comment by cdunn2001** [comment]
Bad news. I had my laptop stolen. The keys were password-protected, so no worries. But I might have to create a new signing key. Hopefully I'll have time this weekend.

**Comment by cdunn2001** [comment]
I just signed with a new signing key. Try it again.

**Comment by cinemast** [comment]
No. Still bad signature: 

```sh
 gpg --verify jsoncpp-0.10.2.tar.gz.asc
gpg: assuming signed data in `jsoncpp-0.10.2.tar.gz'
gpg: Signature made Mon 27 Apr 2015 06:52:06 AM CEST using RSA key ID 2948AE83
gpg: BAD signature from "Christopher Dunn <cdunn2001@gmail.com>"
```

**Comment by cdunn2001** [comment]
That was signed with an older key. It should work now.

**Comment by cinemast** [comment]
It still doesn't work. How do you create the signature? It was already working in the past.

**Comment by cinemast** [comment]
```sh
$> gpg --recv-keys 3FFC2B3B
gpg: requesting key 3FFC2B3B from hkp server pgp.mit.edu
gpg: key 3FFC2B3B: public key "Christopher Dunn <cdunn2001@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
                                                                                       
$> gpg --verify jsoncpp-0.10.2.tar.gz.asc
gpg: assuming signed data in `jsoncpp-0.10.2.tar.gz'
gpg: Signature made Mon 29 Jun 2015 07:35:08 AM CEST using RSA key ID 3FFC2B3B
gpg: BAD signature from "Christopher Dunn <cdunn2001@gmail.com>"

$> cat jsoncpp-0.10.2.tar.gz.asc 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAABAgAGBQJVkNkMAAoJEHxz/rs//Cs7pOAH/1SYlJkt1iADcDD0EHsie80v
StHjptz5Ebq7le3uTTHiAFAx/5/jFQb1FfA3eBMR4RjNi4sKNtoSYz26/Hz/X3tZ
dOt+uzQn5gLnDA9jRviItWg3yGj+U6iyOgxHN6ZL9wreHg//eeORz8LYf9cgXEOd
8UOKM5gPK7KYcXwv8H6Q5weMvqtsmR8xnqOOChgoQgD+ChhS9p1Oh1rQojWg+Pia
FvvgRh0HwC/0PM6BJY03UBCZnDJWKc1zXwS7dLlhJ53L3B92wbiQNT5TGGiAhKHL
ck/AtpYATiO2QX3HOQtphKTZnb3HGxQg0mh1RMcqYI5X60pnYSqGwCQ0wylpnCE=
=PYDo
-----END PGP SIGNATURE-----
```

**Comment by cdunn2001** [comment]
```sh
$ gpg --verify jsoncpp-0.10.2.tar.gz.asc
gpg: assuming signed data in `jsoncpp-0.10.2.tar.gz'
gpg: Signature made Mon Jun 29 00:35:08 2015 CDT using RSA key ID 3FFC2B3B
gpg: Good signature from "Christopher Dunn <cdunn2001@gmail.com>"
$ cat jsoncpp-0.10.2.tar.gz.asc
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAABAgAGBQJVkNkMAAoJEHxz/rs//Cs7pOAH/1SYlJkt1iADcDD0EHsie80v
StHjptz5Ebq7le3uTTHiAFAx/5/jFQb1FfA3eBMR4RjNi4sKNtoSYz26/Hz/X3tZ
dOt+uzQn5gLnDA9jRviItWg3yGj+U6iyOgxHN6ZL9wreHg//eeORz8LYf9cgXEOd
8UOKM5gPK7KYcXwv8H6Q5weMvqtsmR8xnqOOChgoQgD+ChhS9p1Oh1rQojWg+Pia
FvvgRh0HwC/0PM6BJY03UBCZnDJWKc1zXwS7dLlhJ53L3B92wbiQNT5TGGiAhKHL
ck/AtpYATiO2QX3HOQtphKTZnb3HGxQg0mh1RMcqYI5X60pnYSqGwCQ0wylpnCE=
=PYDo
-----END PGP SIGNATURE-----
$ md5 jsoncpp-0.10.2.tar.gz
MD5 (jsoncpp-0.10.2.tar.gz) = c7cbf26153ee6d0c3f4d380c2c51f679
```
Maybe you need to re-download the tarball?

**Comment by cdunn2001** [comment]
Try this one:
* https://github.com/open-source-parsers/jsoncpp/releases/tag/0.10.4

I think I had changed the tag for yours, because I lost the old signing key. But the latest should be signed properly.

**Comment by cinemast** [comment]
Sorry, its still not working. Please ask also someone else to verify. I still get bad signatures for 0.10.4

I don't know whats wrong here. If someone else also has trouble, maybe it is something on your side.

**Comment by cdunn2001** [comment]
I haven't changed the procedure since when it was working. All that changed is the signing key, which I have published.

    make -f dev.makefile sign

> Please ask also someone else to verify.

Ok.

**Comment by cdunn2001** [comment]
* https://github.com/open-source-parsers/jsoncpp/releases/tag/0.10.5

Could you try the signature one more time? I just explicitly copy/pasted my public key armor to the MIT server.

I'll try to get someone else to verify over the weekend.

**Comment by cdunn2001** [comment]
I'm thinking to switch to GitHub's new ["Signature Verification"](https://github.com/blog/2144-gpg-signature-verification). Any objection?

**Comment by cinemast** [comment]
Well its not the same as signing tarballs, but better than having nothing. I will give it a deeper look but anyway it is your decision.

**Comment by baylesj** [comment]
I have added a GPG key to my account to enable commits to be Signature Verified. Other than adding this to a CONTRIBUTING.md, is there any further action? Should we also be signing tarballs? I'd love to satisfactorily close this issue.

**Comment by cinemast** [comment]
Signing tarballs would be great.

**Comment by baylesj** [comment]
I would be open to signing tarballs moving forward but we would need to distribute the private key to more contributors or have @cdunn2001 run all releases moving forward.

**Comment by baylesj** [comment]
Closing as a duplicate of #550 to consolidate discussion on release package signing.
